// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-1yQ4meoSiVMksrRlAksSSieeJDLZAM',
    appId: '1:263113070815:web:73ee29d35b94d75d4db16a',
    messagingSenderId: '263113070815',
    projectId: 'esp32tempmonitor-bd728',
    authDomain: 'esp32tempmonitor-bd728.firebaseapp.com',
    databaseURL: 'https://esp32tempmonitor-bd728-default-rtdb.firebaseio.com',
    storageBucket: 'esp32tempmonitor-bd728.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyb5T8cQMmNdDnmuR7FbILWR8Zvj14QDM',
    appId: '1:263113070815:android:28f00d64f3af0ab84db16a',
    messagingSenderId: '263113070815',
    projectId: 'esp32tempmonitor-bd728',
    databaseURL: 'https://esp32tempmonitor-bd728-default-rtdb.firebaseio.com',
    storageBucket: 'esp32tempmonitor-bd728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2MeQt8p5MN94_Hl3C4GQ44zl9htdH_f8',
    appId: '1:263113070815:ios:69b2d10de5b1e4874db16a',
    messagingSenderId: '263113070815',
    projectId: 'esp32tempmonitor-bd728',
    databaseURL: 'https://esp32tempmonitor-bd728-default-rtdb.firebaseio.com',
    storageBucket: 'esp32tempmonitor-bd728.firebasestorage.app',
    iosBundleId: 'com.application.sensorguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2MeQt8p5MN94_Hl3C4GQ44zl9htdH_f8',
    appId: '1:263113070815:ios:69b2d10de5b1e4874db16a',
    messagingSenderId: '263113070815',
    projectId: 'esp32tempmonitor-bd728',
    databaseURL: 'https://esp32tempmonitor-bd728-default-rtdb.firebaseio.com',
    storageBucket: 'esp32tempmonitor-bd728.firebasestorage.app',
    iosBundleId: 'com.application.sensorguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7-1yQ4meoSiVMksrRlAksSSieeJDLZAM',
    appId: '1:263113070815:web:ec5a7fb447aac6374db16a',
    messagingSenderId: '263113070815',
    projectId: 'esp32tempmonitor-bd728',
    authDomain: 'esp32tempmonitor-bd728.firebaseapp.com',
    databaseURL: 'https://esp32tempmonitor-bd728-default-rtdb.firebaseio.com',
    storageBucket: 'esp32tempmonitor-bd728.firebasestorage.app',
  );
}
